import { Message } from 'discord.js';

export class TranscriptBuilder {
  /**
   * Generates a Flameborn-branded HTML transcript from a list of Discord messages.
   */
  static async generate(messages: Message[], channelName: string, ticketId: string): Promise<string> {
    
    // Process messages into HTML rows
    const messageRows = messages.map(msg => {
      const time = msg.createdAt.toLocaleString();
      const author = msg.author.username;
      const avatar = msg.author.displayAvatarURL({ extension: 'png', size: 64 });
      const content = msg.content.replace(/\n/g, '<br/>'); // Basic newline formatting
      
      let attachmentsHtml = '';
      if (msg.attachments.size > 0) {
        attachmentsHtml = `<div class="attachments">`;
        msg.attachments.forEach(att => {
          if (att.contentType?.startsWith('image/')) {
            attachmentsHtml += `<a href="${att.url}" target="_blank"><img src="${att.url}" class="attachment-img" alt="attachment"/></a>`;
          } else {
            attachmentsHtml += `<a href="${att.url}" target="_blank" class="attachment-file">📎 ${att.name}</a>`;
          }
        });
        attachmentsHtml += `</div>`;
      }

      return `
        <div class="message">
          <img class="avatar" src="${avatar}" alt="${author}" />
          <div class="message-content">
            <div class="header">
              <span class="author">${author}</span>
              <span class="timestamp">${time}</span>
            </div>
            <div class="content">${content}</div>
            ${attachmentsHtml}
          </div>
        </div>
      `;
    }).join('');

    // Wrap in Flameborn-styled HTML shell
    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Transcript: ${channelName}</title>
  <style>
    :root {
      --bg: #1e1e2e;
      --surface: #282a36;
      --text: #f8f8f2;
      --accent: #ff79c6;
      --subtext: #6272a4;
    }
    body {
      margin: 0;
      padding: 0;
      background-color: var(--bg);
      color: var(--text);
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
    .container {
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    .header-banner {
      background-color: var(--surface);
      padding: 30px;
      border-radius: 12px;
      margin-bottom: 30px;
      border-left: 5px solid var(--accent);
      box-shadow: 0 4px 6px rgba(0,0,0,0.3);
    }
    .header-banner h1 {
      margin: 0 0 10px 0;
      color: var(--text);
    }
    .header-banner p {
      margin: 0;
      color: var(--subtext);
    }
    .message {
      display: flex;
      margin-bottom: 20px;
      background-color: var(--surface);
      padding: 15px;
      border-radius: 8px;
    }
    .avatar {
      width: 40px;
      height: 40px;
      border-radius: 50%;
      margin-right: 15px;
    }
    .message-content {
      flex: 1;
    }
    .header {
      margin-bottom: 5px;
    }
    .author {
      font-weight: bold;
      color: var(--accent);
      margin-right: 10px;
    }
    .timestamp {
      font-size: 0.8em;
      color: var(--subtext);
    }
    .content {
      line-height: 1.5;
    }
    .attachments {
      margin-top: 10px;
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
    }
    .attachment-img {
      max-width: 300px;
      max-height: 300px;
      border-radius: 8px;
    }
    .attachment-file {
      display: inline-block;
      padding: 8px 12px;
      background-color: var(--bg);
      color: var(--accent);
      text-decoration: none;
      border-radius: 6px;
      font-size: 0.9em;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header-banner">
      <h1>Ticket Transcript: ${channelName}</h1>
      <p>Ticket ID: #${ticketId} | Generated by Flameborn Bot</p>
    </div>
    <div class="messages">
      ${messageRows}
    </div>
  </div>
</body>
</html>
    `;

    return html;
  }
}
